import express from "express";
import post from "../controllers/post.controller.js";
import protectedRoute from "../middlewares/protectedRoute.js";
const router = express.Router();
router.get("/getPost/:id", post.getPost);
router.get("/user/:username", post.getUserPosts);
router.get("/feedPost", protectedRoute, post.feedPost);
router.post("/create", protectedRoute, post.createPost);
router.put("/like/:id", protectedRoute, post.likeUnLikePost);
router.delete("/delete/:id", protectedRoute, post.deletePost);
router.put("/reply/:id", protectedRoute, post.replyToPost);
export default router;
