import express from "express";
import user from "../controllers/user.controller.js";
import protectedRoute from "../middlewares/protectedRoute.js";
const router = express.Router();
router.get("/profile/:query", user.getUserProfile);
router.post("/signup", user.signup);
router.post("/signin",  user.signin);
router.post("/logout",  user.logout);
router.post("/follow/:id", protectedRoute, user.followUser);
router.post("/unfollow/:id", protectedRoute, user.unFollowUser);
router.put("/update/:id", protectedRoute, user.updateUser);
router.delete("/delete/:id", protectedRoute, user.deleteUser);
export default router;
